# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 05:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161101_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='app_link',
            new_name='project_link',
        ),
    ]
