# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161101_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=b'static/app/images/torgoman.PNG', upload_to=b'uploads'),
        ),
    ]
